### ISSUE TITLE
problem displaying SA word cloud PNG files in  HTML

### ISSUE THREAD

**Issue by AnnaPL8** [navydoc77/natural-disasters#3]
png files had been added to html and they do not display (see example html code below): 

```
<div class=“row text-center”>
    <div class=“col-md-12”>
      <h3>Positive Emotions During National Disasters</h3>
      <a target=“_blank” href=“../static/images/positive_cloud.png”>
        <img src=“../static/images/positive_cloud.png” class=“center-block img-responsive”/>
      </a>
    </div>
  </div>
```

The html file name: sentiment_landing.html (  located in templates folder)

The png file names are: negative_cloud.png, positive_cloud.png
located in static/images
 
if you want to run it please contact Tom

**Comment by fireproofsocks** [comment]
You need to use the proper path in references to your static assets.  Your `templates/` directory is NOT web root; normally Flask considers the repository root to be web root, and static assets are exposed via a configurable prefix ("static" by default).  Secondly, you must use regular straight quotations, e.g. `"`, and not any "smart quotes", e.g. `”` -- that can ruin your code.

Recommendation is to use the `url_for()` method to dynamically reference static assets:

```
<a target="_blank" href="{{ url_for('static', filename='images/negative_cloud.png') }}">
        <img src="{{ url_for('static', filename='images/negative_cloud.png') }}" class="center-block img-responsive"/>
      </a>
```
